x <- fread(paste0(root_dir,"/train.csv"))
test <- fread(paste0(root_dir,"/test.csv"))
d_X<-fread(paste0(dropbox_root_dir,"X.csv"))
d_y<-fread(paste0(dropbox_root_dir,"y.csv"))
d_test<-fread(paste0(dropbox_root_dir,"testData.csv"))
d_y<-t(d_y)
d_x_valid<-fread(paste0(dropbox_root_dir,"x_valid.csv"))
d_y_valid<-fread(paste0(dropbox_root_dir,"y_valid.csv"))
d_y_valid<-t(d_y_valid)